/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as NiveauxRouteImport } from './routes/niveaux'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FinancementRouteImport } from './routes/financement'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BilanRouteImport } from './routes/bilan'
import { Route as IndexRouteImport } from './routes/index'

const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauxRoute = NiveauxRouteImport.update({
  id: '/niveaux',
  path: '/niveaux',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementRoute = FinancementRouteImport.update({
  id: '/financement',
  path: '/financement',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanRoute = BilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/financement': typeof FinancementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/niveaux': typeof NiveauxRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/financement': typeof FinancementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/niveaux': typeof NiveauxRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilan': typeof BilanRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/financement': typeof FinancementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/niveaux': typeof NiveauxRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilan'
    | '/confidentialite'
    | '/contact'
    | '/evaluation'
    | '/financement'
    | '/mentions-legales'
    | '/niveaux'
    | '/simulateur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bilan'
    | '/confidentialite'
    | '/contact'
    | '/evaluation'
    | '/financement'
    | '/mentions-legales'
    | '/niveaux'
    | '/simulateur'
  id:
    | '__root__'
    | '/'
    | '/bilan'
    | '/confidentialite'
    | '/contact'
    | '/evaluation'
    | '/financement'
    | '/mentions-legales'
    | '/niveaux'
    | '/simulateur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilanRoute: typeof BilanRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EvaluationRoute: typeof EvaluationRoute
  FinancementRoute: typeof FinancementRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NiveauxRoute: typeof NiveauxRoute
  SimulateurRoute: typeof SimulateurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveaux': {
      id: '/niveaux'
      path: '/niveaux'
      fullPath: '/niveaux'
      preLoaderRoute: typeof NiveauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financement': {
      id: '/financement'
      path: '/financement'
      fullPath: '/financement'
      preLoaderRoute: typeof FinancementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan': {
      id: '/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof BilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilanRoute: BilanRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EvaluationRoute: EvaluationRoute,
  FinancementRoute: FinancementRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NiveauxRoute: NiveauxRoute,
  SimulateurRoute: SimulateurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
