/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TestRapideRouteImport } from './routes/test-rapide'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PartenaireRouteImport } from './routes/partenaire'
import { Route as NiveauxRouteImport } from './routes/niveaux'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as FinancementRouteImport } from './routes/financement'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccompagnementAdministratifRouteImport } from './routes/accompagnement-administratif'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinancementIndexRouteImport } from './routes/financement.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SessionsCohortIdRouteImport } from './routes/sessions.$cohortId'
import { Route as QualificationAttemptIdRouteImport } from './routes/qualification.$attemptId'
import { Route as PasserTestTokenRouteImport } from './routes/passer-test.$token'
import { Route as FinancementCpfRouteImport } from './routes/financement.cpf'
import { Route as BilanTestAttemptIdRouteImport } from './routes/bilan-test.$attemptId'
import { Route as ApiCaptureLeadRouteImport } from './routes/api.capture-lead'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportingRouteImport } from './routes/admin.reporting'
import { Route as AdminPartenairesRouteImport } from './routes/admin.partenaires'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCohortesRouteImport } from './routes/admin.cohortes'
import { Route as PartenaireLeadsLeadIdRouteImport } from './routes/partenaire.leads.$leadId'
import { Route as AdminPartenairesNewRouteImport } from './routes/admin.partenaires.new'
import { Route as AdminLeadsLeadIdRouteImport } from './routes/admin.leads.$leadId'
import { Route as AdminCohortesNouveauRouteImport } from './routes/admin.cohortes.nouveau'
import { Route as AdminCohortesCohortIdRouteImport } from './routes/admin.cohortes.$cohortId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRapideRoute = TestRapideRouteImport.update({
  id: '/test-rapide',
  path: '/test-rapide',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRoute = PartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauxRoute = NiveauxRouteImport.update({
  id: '/niveaux',
  path: '/niveaux',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementRoute = FinancementRouteImport.update({
  id: '/financement',
  path: '/financement',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccompagnementAdministratifRoute =
  AccompagnementAdministratifRouteImport.update({
    id: '/accompagnement-administratif',
    path: '/accompagnement-administratif',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementIndexRoute = FinancementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinancementRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SessionsCohortIdRoute = SessionsCohortIdRouteImport.update({
  id: '/$cohortId',
  path: '/$cohortId',
  getParentRoute: () => SessionsRoute,
} as any)
const QualificationAttemptIdRoute = QualificationAttemptIdRouteImport.update({
  id: '/qualification/$attemptId',
  path: '/qualification/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PasserTestTokenRoute = PasserTestTokenRouteImport.update({
  id: '/passer-test/$token',
  path: '/passer-test/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementCpfRoute = FinancementCpfRouteImport.update({
  id: '/cpf',
  path: '/cpf',
  getParentRoute: () => FinancementRoute,
} as any)
const BilanTestAttemptIdRoute = BilanTestAttemptIdRouteImport.update({
  id: '/bilan-test/$attemptId',
  path: '/bilan-test/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptureLeadRoute = ApiCaptureLeadRouteImport.update({
  id: '/api/capture-lead',
  path: '/api/capture-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartenairesRoute = AdminPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortesRoute = AdminCohortesRouteImport.update({
  id: '/cohortes',
  path: '/cohortes',
  getParentRoute: () => AdminRoute,
} as any)
const PartenaireLeadsLeadIdRoute = PartenaireLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => PartenaireRoute,
} as any)
const AdminPartenairesNewRoute = AdminPartenairesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPartenairesRoute,
} as any)
const AdminLeadsLeadIdRoute = AdminLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminCohortesNouveauRoute = AdminCohortesNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AdminCohortesRoute,
} as any)
const AdminCohortesCohortIdRoute = AdminCohortesCohortIdRouteImport.update({
  id: '/$cohortId',
  path: '/$cohortId',
  getParentRoute: () => AdminCohortesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accompagnement-administratif': typeof AccompagnementAdministratifRoute
  '/admin': typeof AdminRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/financement': typeof FinancementRouteWithChildren
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/niveaux': typeof NiveauxRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/test-rapide': typeof TestRapideRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/cohortes': typeof AdminCohortesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/partenaires': typeof AdminPartenairesRouteWithChildren
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/capture-lead': typeof ApiCaptureLeadRoute
  '/bilan-test/$attemptId': typeof BilanTestAttemptIdRoute
  '/financement/cpf': typeof FinancementCpfRoute
  '/passer-test/$token': typeof PasserTestTokenRoute
  '/qualification/$attemptId': typeof QualificationAttemptIdRoute
  '/sessions/$cohortId': typeof SessionsCohortIdRoute
  '/admin/': typeof AdminIndexRoute
  '/financement/': typeof FinancementIndexRoute
  '/admin/cohortes/$cohortId': typeof AdminCohortesCohortIdRoute
  '/admin/cohortes/nouveau': typeof AdminCohortesNouveauRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/partenaires/new': typeof AdminPartenairesNewRoute
  '/partenaire/leads/$leadId': typeof PartenaireLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accompagnement-administratif': typeof AccompagnementAdministratifRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/niveaux': typeof NiveauxRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/test-rapide': typeof TestRapideRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/cohortes': typeof AdminCohortesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/partenaires': typeof AdminPartenairesRouteWithChildren
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/capture-lead': typeof ApiCaptureLeadRoute
  '/bilan-test/$attemptId': typeof BilanTestAttemptIdRoute
  '/financement/cpf': typeof FinancementCpfRoute
  '/passer-test/$token': typeof PasserTestTokenRoute
  '/qualification/$attemptId': typeof QualificationAttemptIdRoute
  '/sessions/$cohortId': typeof SessionsCohortIdRoute
  '/admin': typeof AdminIndexRoute
  '/financement': typeof FinancementIndexRoute
  '/admin/cohortes/$cohortId': typeof AdminCohortesCohortIdRoute
  '/admin/cohortes/nouveau': typeof AdminCohortesNouveauRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/partenaires/new': typeof AdminPartenairesNewRoute
  '/partenaire/leads/$leadId': typeof PartenaireLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accompagnement-administratif': typeof AccompagnementAdministratifRoute
  '/admin': typeof AdminRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/financement': typeof FinancementRouteWithChildren
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/niveaux': typeof NiveauxRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/test-rapide': typeof TestRapideRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/cohortes': typeof AdminCohortesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/partenaires': typeof AdminPartenairesRouteWithChildren
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/capture-lead': typeof ApiCaptureLeadRoute
  '/bilan-test/$attemptId': typeof BilanTestAttemptIdRoute
  '/financement/cpf': typeof FinancementCpfRoute
  '/passer-test/$token': typeof PasserTestTokenRoute
  '/qualification/$attemptId': typeof QualificationAttemptIdRoute
  '/sessions/$cohortId': typeof SessionsCohortIdRoute
  '/admin/': typeof AdminIndexRoute
  '/financement/': typeof FinancementIndexRoute
  '/admin/cohortes/$cohortId': typeof AdminCohortesCohortIdRoute
  '/admin/cohortes/nouveau': typeof AdminCohortesNouveauRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/partenaires/new': typeof AdminPartenairesNewRoute
  '/partenaire/leads/$leadId': typeof PartenaireLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accompagnement-administratif'
    | '/admin'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/financement'
    | '/formations'
    | '/login'
    | '/mentions-legales'
    | '/mon-espace'
    | '/niveaux'
    | '/partenaire'
    | '/sessions'
    | '/test-rapide'
    | '/unsubscribe'
    | '/admin/cohortes'
    | '/admin/leads'
    | '/admin/partenaires'
    | '/admin/reporting'
    | '/admin/users'
    | '/api/capture-lead'
    | '/bilan-test/$attemptId'
    | '/financement/cpf'
    | '/passer-test/$token'
    | '/qualification/$attemptId'
    | '/sessions/$cohortId'
    | '/admin/'
    | '/financement/'
    | '/admin/cohortes/$cohortId'
    | '/admin/cohortes/nouveau'
    | '/admin/leads/$leadId'
    | '/admin/partenaires/new'
    | '/partenaire/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accompagnement-administratif'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/formations'
    | '/login'
    | '/mentions-legales'
    | '/mon-espace'
    | '/niveaux'
    | '/partenaire'
    | '/sessions'
    | '/test-rapide'
    | '/unsubscribe'
    | '/admin/cohortes'
    | '/admin/leads'
    | '/admin/partenaires'
    | '/admin/reporting'
    | '/admin/users'
    | '/api/capture-lead'
    | '/bilan-test/$attemptId'
    | '/financement/cpf'
    | '/passer-test/$token'
    | '/qualification/$attemptId'
    | '/sessions/$cohortId'
    | '/admin'
    | '/financement'
    | '/admin/cohortes/$cohortId'
    | '/admin/cohortes/nouveau'
    | '/admin/leads/$leadId'
    | '/admin/partenaires/new'
    | '/partenaire/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/accompagnement-administratif'
    | '/admin'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/financement'
    | '/formations'
    | '/login'
    | '/mentions-legales'
    | '/mon-espace'
    | '/niveaux'
    | '/partenaire'
    | '/sessions'
    | '/test-rapide'
    | '/unsubscribe'
    | '/admin/cohortes'
    | '/admin/leads'
    | '/admin/partenaires'
    | '/admin/reporting'
    | '/admin/users'
    | '/api/capture-lead'
    | '/bilan-test/$attemptId'
    | '/financement/cpf'
    | '/passer-test/$token'
    | '/qualification/$attemptId'
    | '/sessions/$cohortId'
    | '/admin/'
    | '/financement/'
    | '/admin/cohortes/$cohortId'
    | '/admin/cohortes/nouveau'
    | '/admin/leads/$leadId'
    | '/admin/partenaires/new'
    | '/partenaire/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccompagnementAdministratifRoute: typeof AccompagnementAdministratifRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FinancementRoute: typeof FinancementRouteWithChildren
  FormationsRoute: typeof FormationsRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MonEspaceRoute: typeof MonEspaceRoute
  NiveauxRoute: typeof NiveauxRoute
  PartenaireRoute: typeof PartenaireRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
  TestRapideRoute: typeof TestRapideRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiCaptureLeadRoute: typeof ApiCaptureLeadRoute
  BilanTestAttemptIdRoute: typeof BilanTestAttemptIdRoute
  PasserTestTokenRoute: typeof PasserTestTokenRoute
  QualificationAttemptIdRoute: typeof QualificationAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-rapide': {
      id: '/test-rapide'
      path: '/test-rapide'
      fullPath: '/test-rapide'
      preLoaderRoute: typeof TestRapideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire': {
      id: '/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof PartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveaux': {
      id: '/niveaux'
      path: '/niveaux'
      fullPath: '/niveaux'
      preLoaderRoute: typeof NiveauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financement': {
      id: '/financement'
      path: '/financement'
      fullPath: '/financement'
      preLoaderRoute: typeof FinancementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accompagnement-administratif': {
      id: '/accompagnement-administratif'
      path: '/accompagnement-administratif'
      fullPath: '/accompagnement-administratif'
      preLoaderRoute: typeof AccompagnementAdministratifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financement/': {
      id: '/financement/'
      path: '/'
      fullPath: '/financement/'
      preLoaderRoute: typeof FinancementIndexRouteImport
      parentRoute: typeof FinancementRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sessions/$cohortId': {
      id: '/sessions/$cohortId'
      path: '/$cohortId'
      fullPath: '/sessions/$cohortId'
      preLoaderRoute: typeof SessionsCohortIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/qualification/$attemptId': {
      id: '/qualification/$attemptId'
      path: '/qualification/$attemptId'
      fullPath: '/qualification/$attemptId'
      preLoaderRoute: typeof QualificationAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passer-test/$token': {
      id: '/passer-test/$token'
      path: '/passer-test/$token'
      fullPath: '/passer-test/$token'
      preLoaderRoute: typeof PasserTestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financement/cpf': {
      id: '/financement/cpf'
      path: '/cpf'
      fullPath: '/financement/cpf'
      preLoaderRoute: typeof FinancementCpfRouteImport
      parentRoute: typeof FinancementRoute
    }
    '/bilan-test/$attemptId': {
      id: '/bilan-test/$attemptId'
      path: '/bilan-test/$attemptId'
      fullPath: '/bilan-test/$attemptId'
      preLoaderRoute: typeof BilanTestAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capture-lead': {
      id: '/api/capture-lead'
      path: '/api/capture-lead'
      fullPath: '/api/capture-lead'
      preLoaderRoute: typeof ApiCaptureLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partenaires': {
      id: '/admin/partenaires'
      path: '/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AdminPartenairesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohortes': {
      id: '/admin/cohortes'
      path: '/cohortes'
      fullPath: '/admin/cohortes'
      preLoaderRoute: typeof AdminCohortesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partenaire/leads/$leadId': {
      id: '/partenaire/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/partenaire/leads/$leadId'
      preLoaderRoute: typeof PartenaireLeadsLeadIdRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/admin/partenaires/new': {
      id: '/admin/partenaires/new'
      path: '/new'
      fullPath: '/admin/partenaires/new'
      preLoaderRoute: typeof AdminPartenairesNewRouteImport
      parentRoute: typeof AdminPartenairesRoute
    }
    '/admin/leads/$leadId': {
      id: '/admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/admin/leads/$leadId'
      preLoaderRoute: typeof AdminLeadsLeadIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/cohortes/nouveau': {
      id: '/admin/cohortes/nouveau'
      path: '/nouveau'
      fullPath: '/admin/cohortes/nouveau'
      preLoaderRoute: typeof AdminCohortesNouveauRouteImport
      parentRoute: typeof AdminCohortesRoute
    }
    '/admin/cohortes/$cohortId': {
      id: '/admin/cohortes/$cohortId'
      path: '/$cohortId'
      fullPath: '/admin/cohortes/$cohortId'
      preLoaderRoute: typeof AdminCohortesCohortIdRouteImport
      parentRoute: typeof AdminCohortesRoute
    }
  }
}

interface AdminCohortesRouteChildren {
  AdminCohortesCohortIdRoute: typeof AdminCohortesCohortIdRoute
  AdminCohortesNouveauRoute: typeof AdminCohortesNouveauRoute
}

const AdminCohortesRouteChildren: AdminCohortesRouteChildren = {
  AdminCohortesCohortIdRoute: AdminCohortesCohortIdRoute,
  AdminCohortesNouveauRoute: AdminCohortesNouveauRoute,
}

const AdminCohortesRouteWithChildren = AdminCohortesRoute._addFileChildren(
  AdminCohortesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsLeadIdRoute: typeof AdminLeadsLeadIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsLeadIdRoute: AdminLeadsLeadIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminPartenairesRouteChildren {
  AdminPartenairesNewRoute: typeof AdminPartenairesNewRoute
}

const AdminPartenairesRouteChildren: AdminPartenairesRouteChildren = {
  AdminPartenairesNewRoute: AdminPartenairesNewRoute,
}

const AdminPartenairesRouteWithChildren =
  AdminPartenairesRoute._addFileChildren(AdminPartenairesRouteChildren)

interface AdminRouteChildren {
  AdminCohortesRoute: typeof AdminCohortesRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminPartenairesRoute: typeof AdminPartenairesRouteWithChildren
  AdminReportingRoute: typeof AdminReportingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCohortesRoute: AdminCohortesRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminPartenairesRoute: AdminPartenairesRouteWithChildren,
  AdminReportingRoute: AdminReportingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FinancementRouteChildren {
  FinancementCpfRoute: typeof FinancementCpfRoute
  FinancementIndexRoute: typeof FinancementIndexRoute
}

const FinancementRouteChildren: FinancementRouteChildren = {
  FinancementCpfRoute: FinancementCpfRoute,
  FinancementIndexRoute: FinancementIndexRoute,
}

const FinancementRouteWithChildren = FinancementRoute._addFileChildren(
  FinancementRouteChildren,
)

interface PartenaireRouteChildren {
  PartenaireLeadsLeadIdRoute: typeof PartenaireLeadsLeadIdRoute
}

const PartenaireRouteChildren: PartenaireRouteChildren = {
  PartenaireLeadsLeadIdRoute: PartenaireLeadsLeadIdRoute,
}

const PartenaireRouteWithChildren = PartenaireRoute._addFileChildren(
  PartenaireRouteChildren,
)

interface SessionsRouteChildren {
  SessionsCohortIdRoute: typeof SessionsCohortIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsCohortIdRoute: SessionsCohortIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccompagnementAdministratifRoute: AccompagnementAdministratifRoute,
  AdminRoute: AdminRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FinancementRoute: FinancementRouteWithChildren,
  FormationsRoute: FormationsRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MonEspaceRoute: MonEspaceRoute,
  NiveauxRoute: NiveauxRoute,
  PartenaireRoute: PartenaireRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
  TestRapideRoute: TestRapideRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiCaptureLeadRoute: ApiCaptureLeadRoute,
  BilanTestAttemptIdRoute: BilanTestAttemptIdRoute,
  PasserTestTokenRoute: PasserTestTokenRoute,
  QualificationAttemptIdRoute: QualificationAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
